# Generated by Django 4.0.2 on 2022-04-10 19:15

import Gym_at_the_Moscow.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administratorsclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Администратор',
                'verbose_name_plural': 'Администраторы',
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_gym', models.CharField(choices=[('ADMIN', 'Администратор'), ('EQUIP', 'Техник'), ('ACCOU', 'Бухгалтер'), ('CLEAN', 'Уборщица')], default=' ', max_length=5, verbose_name='Должность')),
                ('full_name', models.CharField(max_length=40, verbose_name='ФИО')),
                ('age', models.IntegerField(null=True, verbose_name='Возраст')),
                ('phone', models.CharField(max_length=12, validators=[Gym_at_the_Moscow.models.mobile_validate], verbose_name='Телефон')),
                ('trainer_email', models.EmailField(blank=True, max_length=254, verbose_name='Почта')),
                ('time_create', models.DateTimeField(auto_now=True, verbose_name='Регистрация')),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='personnel/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Персонал',
                'verbose_name_plural': 'Персонал',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=30, verbose_name='Товар')),
                ('amount', models.CharField(max_length=30, verbose_name='Количество')),
                ('price', models.CharField(max_length=30, verbose_name='Цена, руб.')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=40, verbose_name='ФИО')),
                ('age', models.IntegerField(null=True, verbose_name='Возраст')),
                ('phone', models.CharField(max_length=12, validators=[Gym_at_the_Moscow.models.mobile_validate], verbose_name='Телефон')),
                ('trainer_email', models.EmailField(blank=True, max_length=254, verbose_name='Почта')),
                ('time_create', models.DateTimeField(auto_now=True, verbose_name='Регистрация')),
                ('about_trainer', models.TextField(blank=True, max_length=2000, verbose_name='О тренере')),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='trainer/', verbose_name='Фото')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренеры',
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=12, verbose_name='День недели')),
                ('administrator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Gym_at_the_Moscow.administratorsclass', verbose_name='Администратор')),
                ('trainer_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Gym_at_the_Moscow.trainer', verbose_name='Дежурный тренер')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписание',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateField(blank=True, default=None, null=True, verbose_name='День продажи')),
                ('what', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Gym_at_the_Moscow.product', verbose_name='Какой товар продан')),
                ('who_ad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Gym_at_the_Moscow.administratorsclass', verbose_name='Администратор продал')),
                ('who_tr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Gym_at_the_Moscow.trainer', verbose_name='Тренер продал')),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажи',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=40, verbose_name='ФИО')),
                ('gender', models.CharField(choices=[('M', 'Мужчина'), ('F', 'Женщина')], default='M', max_length=1, verbose_name='Пол')),
                ('age', models.IntegerField(null=True, verbose_name='Возраст')),
                ('phone', models.CharField(max_length=12, validators=[Gym_at_the_Moscow.models.mobile_validate], verbose_name='Телефон')),
                ('client_email', models.EmailField(blank=True, max_length=254, verbose_name='Почта')),
                ('time_create', models.DateTimeField(auto_now=True, verbose_name='Регистрация')),
                ('abonnement', models.CharField(choices=[('D', 'Дневной'), ('E', 'Вечерний'), ('F', 'Свободный'), ('X', 'Истёк'), ('N', 'Нет')], default=' ', max_length=1, verbose_name='Абонемент')),
                ('date_ab', models.DateField(blank=True, default=None, null=True, verbose_name='Срок действия абонемента')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Gym_at_the_Moscow.trainer', verbose_name='Тренер')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.AddField(
            model_name='administratorsclass',
            name='admins',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Gym_at_the_Moscow.personnel', verbose_name='Администратор'),
        ),
    ]
