# Generated by Django 4.0.2 on 2022-04-11 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym_at_the_Moscow', '0002_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abonnement', models.CharField(choices=[('D', 'Дневной'), ('E', 'Вечерний'), ('F', 'Свободный'), ('X', 'Истёк'), ('N', 'Нет')], default=' ', max_length=1, verbose_name='Абонемент')),
                ('time', models.CharField(max_length=100, verbose_name='Время посещения')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
            ],
        ),
    ]
