# Generated by Django 4.0.2 on 2022-04-11 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym_at_the_Moscow', '0004_alter_abonnement_options_alter_abonnement_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='abonnement',
            field=models.CharField(max_length=100, verbose_name='Абонемент'),
        ),
    ]
